version: v1.0
name: Prod Deploy
agent:
  machine:
    type: e1-standard-2

  containers:
    - name: main
      image: 'registry.semaphoreci.com/node:14'
blocks:
  - name: Deploy to Production
    task:
      secrets:
        - name: bc-git-secret
#        - name: bc-npm-secret
        - name: mb-semantic-test-secret
      jobs:
        - name: Deploy
          commands:
            - cache restore mb-semantic-test-version-$SEMAPHORE_GIT_SHA
            - export $(cat version.txt)
            - rm version.txt
            - checkout
            - git remote rm origin
            - git remote add origin https://$GH_USER:$GH_TOKEN@github.com/milosbugarinovic/semantic-test.git
            - git checkout tags/v$VERSION -b tmp-prod-branch
            - npm ci
            - npm run build
            - git tag v$VERSION-prod && git push origin --tags
#            - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
#            - npm config set unsafe-perm true
#            - npm publish --access public
    skip:
      when: branch != 'main'
