version: v1.0
name: Test
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy production
    task:
      secrets:
        - name: mb-semantic-test-secret
      jobs:
        - name: Deploy Production
          commands:
            - sem-version node 14.15.1
            - checkout
            - npm ci
            - npm publish
