version: v1.0
name: Test
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy production
    task:
      secrets:
        - name: mb-semantic-test-secret
      jobs:
        - name: Deploy Production
          commands:
            - sem-version node 14.15.1
            - cache restore version-$SEMAPHORE_GIT_SHA
            - export $(cat version.txt)
            - rm version.txt
            - checkout
            - git remote rm origin
            - git remote add origin https://$GH_USER:$GH_TOKEN@github.com/milosbugarinovic/semantic-test.git
            - git checkout tags/v$VERSION -b tmp-branch
            - npm ci
            - npm publish
            - export VERSION=$VERSION-prod
            - git tag v$VERSION && git push origin --tags


